import { Buffer } from 'node:buffer';
import { generateKeyPairSync, sign as signMessage } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { canonicalJson, normalizeP256LowS, p256KeyId, type P256SigningKeyDescriptor } from '@echo-brain/federation-protocol';
import { ORGANIZATION_MEMBER_READABLE_POLICY_ID, organizationMemberReadablePolicyContractSha256 } from '@echo-brain/organization-protocol';
import { canonicalOrganizationMemberReadablePermissionCheckDecisionBytes, createOrganizationMemberReadablePermissionCheckRequest, organizationMemberReadablePermissionProviderEventSha256, validateOrganizationMemberReadablePermissionCheckDecision, validateOrganizationMemberReadablePermissionCheckRequest } from '../src/index.js';

const digest = (character: string): `sha256:${string}` => `sha256:${character.repeat(64)}`;
function key(): { descriptor: P256SigningKeyDescriptor; sign(bytes: Buffer): Promise<Buffer> } { const pair=generateKeyPairSync('ec',{namedCurve:'prime256v1'}); const publicKey=pair.publicKey.export({format:'der',type:'spki'}); if (!Buffer.isBuffer(publicKey)) throw new Error('key'); return { descriptor:{key_id:p256KeyId(publicKey),algorithm:'ecdsa-p256-sha256-der-low-s',public_key_spki_der_base64:publicKey.toString('base64')}, async sign(bytes) { return normalizeP256LowS(signMessage('sha256',bytes,{key:pair.privateKey,dsaEncoding:'der'})); } }; }
const ids = { authority:'oau_00000000-0000-4000-8000-000000000001', organization:'org_00000000-0000-4000-8000-000000000001', enrollment:'enr_00000000-0000-4000-8000-000000000001', installation:'ins_00000000-0000-4000-8000-000000000001' };
describe('organization-member-readable permission check', () => {
  it('signs a schema-v3 content-free request bound to its policy contract and provider event', async () => {
    const signing=key(); const request=await createOrganizationMemberReadablePermissionCheckRequest({request_id:'pcr_00000000-0000-4000-8000-000000000001',authority_id:ids.authority,authority_key_id:digest('a'),organization_id:ids.organization,enrollment_id:ids.enrollment,installation_id:ids.installation,installation_signing_key:signing.descriptor,provider:'slack',provider_issuer:'https://slack.com',provider_tenant_kind:'workspace',provider_tenant_id:'T012ABCDEF',provider_enterprise_id:null,provider_connection_subject_id:'U012BOTUSER',provider_connection_bot_id:'B012BOTID',provider_connection_app_id:'A012APPID',provider_subject_kind:'human_user',provider_subject_id:'U012REVIEWER',adapter_kind:'approval-surface',adapter_id:'slack-reactions',adapter_instance_id:'default',adapter_version:'1.0.0',approval_id:'b'.repeat(64),channel_id:'C012CHANNEL',message_ts:'1754900000.000100',reaction_name:'white_check_mark',approve_reaction:'white_check_mark',reject_reaction:'x',release_draft_sha256:digest('c'),approval_presentation_sha256:digest('d'),requested_at:'2026-08-12T12:00:00.000Z'},signing.sign);
    expect(request.schema_version).toBe(3); expect(request.policy_id).toBe(ORGANIZATION_MEMBER_READABLE_POLICY_ID); expect(request.provider_event_sha256).toBe(organizationMemberReadablePermissionProviderEventSha256(request)); expect(() => validateOrganizationMemberReadablePermissionCheckRequest({...request,policy_id:'restricted-reviewer-v1'})).toThrow();
  });
  it('requires the closed policy fields and nulls all proof fields on a denial', () => {
    expect(validateOrganizationMemberReadablePermissionCheckDecision({schema_version:3,kind:'echo-organization-permission-check-decision',request_sha256:digest('a'),provider_event_sha256:digest('b'),allowed:false,reason_code:'installation_inactive',policy_id:ORGANIZATION_MEMBER_READABLE_POLICY_ID,policy_contract_sha256:organizationMemberReadablePolicyContractSha256(),principal_id:null,membership_id:null,adapter_binding_id:null,permission_grant_id:null,evaluated_at:'2026-08-12T12:00:00.000Z',authorization_audit_event_id:null,authorization_audit_entry_sha256:null,release_draft_sha256:null,approval_presentation_sha256:null,semantic_intent_sha256:null,message_presentation_sha256:null})).toMatchObject({allowed:false});
  });
  it('serializes both allowed and denied closed decisions as their exact bounded canonical bytes', () => {
    const denial={schema_version:3,kind:'echo-organization-permission-check-decision',request_sha256:digest('a'),provider_event_sha256:digest('b'),allowed:false,reason_code:'installation_inactive',policy_id:ORGANIZATION_MEMBER_READABLE_POLICY_ID,policy_contract_sha256:organizationMemberReadablePolicyContractSha256(),principal_id:null,membership_id:null,adapter_binding_id:null,permission_grant_id:null,evaluated_at:'2026-08-12T12:00:00.000Z',authorization_audit_event_id:null,authorization_audit_entry_sha256:null,release_draft_sha256:null,approval_presentation_sha256:null,semantic_intent_sha256:null,message_presentation_sha256:null} as const;
    const allow={...denial,allowed:true,reason_code:'active_organization_member_readable_notice_v1',principal_id:'prn_00000000-0000-4000-8000-000000000001',membership_id:'mem_00000000-0000-4000-8000-000000000001',adapter_binding_id:'bnd_00000000-0000-4000-8000-000000000001',permission_grant_id:'pgr_00000000-0000-4000-8000-000000000001',authorization_audit_event_id:'aud_00000000-0000-4000-8000-000000000001',authorization_audit_entry_sha256:digest('c'),release_draft_sha256:digest('d'),approval_presentation_sha256:digest('e'),semantic_intent_sha256:digest('f'),message_presentation_sha256:digest('0')} as const;
    for (const decision of [allow,denial]) expect(Buffer.from(canonicalOrganizationMemberReadablePermissionCheckDecisionBytes(decision)).toString('utf8')).toBe(canonicalJson(decision));
  });
});
