export const TRUSTED_PROXY_AUTHORIZATION_HEADER: string;
export const TRUSTED_PROXY_CLIENT_ID_HEADER: string;
export const ORGANIZATION_API_AUTHORITY_DESCRIPTOR_PATH: string;
export const ORGANIZATION_API_ADMIN_OVERVIEW_PATH: string;
