export {
  ORGANIZATION_API_PERSON_OIDC_BEGIN_PATH as PERSON_SESSION_OIDC_BEGIN_PATH,
  ORGANIZATION_API_PERSON_OIDC_CALLBACK_PATH as PERSON_SESSION_OIDC_CALLBACK_PATH,
  ORGANIZATION_API_PERSON_SESSION_REFRESH_PATH as PERSON_SESSION_REFRESH_PATH,
  ORGANIZATION_API_PERSON_SESSION_REVOCATIONS_PATH as PERSON_SESSION_REVOCATIONS_PATH,
} from '@echo-brain/organization-api';
