import { canonicalJsonBytes, canonicalSha256, createSignedDocumentWithKey, verifyP256SigningKeyDescriptor, verifySignedDocument } from '@echo-brain/federation-protocol';
import type { P256SigningKeyDescriptor, Sha256Digest } from '@echo-brain/federation-protocol';
import { ORGANIZATION_MEMBER_READABLE_ALLOW_REASON_CODE, ORGANIZATION_MEMBER_READABLE_POLICY_ID, ORGANIZATION_MEMBER_READABLE_REACTION_PATTERN, organizationMemberReadablePolicyContractSha256, type CanonicalPayloadSigner } from '@echo-brain/organization-protocol';
import type { OrganizationMemberReadablePermissionCheckDecisionV3, OrganizationMemberReadablePermissionCheckRequestPayloadV3, OrganizationMemberReadablePermissionCheckRequestV3 } from './contracts.js';
import { ORGANIZATION_API_PERMISSION_CHECKS_PATH } from './http.js';
import { asRecord, assertDigest, assertExactKeys, assertId, assertOnlyEnumerableDataProperties, assertPatternString, assertString, assertTimestamp, fail, MAX_ORGANIZATION_API_BODY_BYTES, validateIntegrity } from './validation.js';

const fields = ['authority_id','authority_key_id','organization_id','enrollment_id','installation_id','installation_key_id','provider','provider_issuer','provider_tenant_kind','provider_tenant_id','provider_enterprise_id','provider_connection_subject_id','provider_connection_bot_id','provider_connection_app_id','provider_subject_kind','provider_subject_id','adapter_kind','adapter_id','adapter_instance_id','adapter_version','action','approval_id','channel_id','message_ts','reaction_name','approve_reaction','reject_reaction','policy_id','policy_contract_sha256','release_draft_sha256','approval_presentation_sha256','http_method','http_path'] as const;
export const ORGANIZATION_MEMBER_READABLE_PERMISSION_DENIAL_REASON_CODES = Object.freeze(['installation_inactive','no_active_link_binding_or_grant','provider_unavailable','provider_identity_mismatch','provider_reaction_not_observed','target_membership_inactive'] as const);
export type OrganizationMemberReadablePermissionDenialReasonCodeV3 = (typeof ORGANIZATION_MEMBER_READABLE_PERMISSION_DENIAL_REASON_CODES)[number];
const requestKeys = ['schema_version','kind','request_id',...fields,'provider_event_sha256','requested_at','integrity'] as const;
export type OrganizationMemberReadablePermissionProviderEventInput = Pick<OrganizationMemberReadablePermissionCheckRequestPayloadV3, (typeof fields)[number]>;
export function organizationMemberReadablePermissionProviderEvent(input: OrganizationMemberReadablePermissionProviderEventInput): OrganizationMemberReadablePermissionProviderEventInput { return Object.fromEntries(fields.map((field) => [field,input[field]])) as OrganizationMemberReadablePermissionProviderEventInput; }
export function organizationMemberReadablePermissionProviderEventSha256(input: OrganizationMemberReadablePermissionProviderEventInput): Sha256Digest { return canonicalSha256({schema_version:3,kind:'echo-organization-permission-provider-event',...organizationMemberReadablePermissionProviderEvent(input)}); }
function assertRequestFields(record: Record<string, unknown>, label: string): void {
  assertId(record.request_id,'pcr',`${label} request_id`); assertId(record.authority_id,'oau',`${label} authority_id`); assertDigest(record.authority_key_id,`${label} authority_key_id`); assertId(record.organization_id,'org',`${label} organization_id`); assertId(record.enrollment_id,'enr',`${label} enrollment_id`); assertId(record.installation_id,'ins',`${label} installation_id`); assertDigest(record.installation_key_id,`${label} installation_key_id`);
  if (record.provider !== 'slack' || record.provider_issuer !== 'https://slack.com' || record.provider_tenant_kind !== 'workspace' || record.provider_subject_kind !== 'human_user' || record.adapter_kind !== 'approval-surface') fail(`${label} provider or adapter kind is unsupported`);
  assertPatternString(record.provider_tenant_id,`${label} provider_tenant_id`,128,/^T[A-Z0-9]{2,}$/); if (record.provider_enterprise_id !== null) assertPatternString(record.provider_enterprise_id,`${label} provider_enterprise_id`,128,/^E[A-Z0-9]{2,}$/); assertPatternString(record.provider_connection_subject_id,`${label} provider_connection_subject_id`,128,/^[UW][A-Z0-9]{2,}$/); assertPatternString(record.provider_connection_bot_id,`${label} provider_connection_bot_id`,128,/^B[A-Z0-9]{2,}$/); if (record.provider_connection_app_id !== null) assertPatternString(record.provider_connection_app_id,`${label} provider_connection_app_id`,128,/^A[A-Z0-9]{2,}$/); assertPatternString(record.provider_subject_id,`${label} provider_subject_id`,128,/^[UW][A-Z0-9]{2,}$/);
  for (const field of ['adapter_id','adapter_instance_id','channel_id'] as const) assertString(record[field],`${label} ${field}`,128); assertString(record.adapter_version,`${label} adapter_version`,64); assertPatternString(record.approval_id,`${label} approval_id`,256,/^[0-9a-f]{64}$/); assertPatternString(record.message_ts,`${label} message_ts`,64,/^\d{1,16}\.\d{1,16}$/);
  for (const field of ['reaction_name','approve_reaction','reject_reaction'] as const) assertPatternString(record[field],`${label} ${field}`,64,ORGANIZATION_MEMBER_READABLE_REACTION_PATTERN); if (record.approve_reaction === record.reject_reaction || record.reaction_name !== record.approve_reaction) fail(`${label} selected reaction does not bind the frozen approval pair`);
  if (record.action !== 'approve' || record.policy_id !== ORGANIZATION_MEMBER_READABLE_POLICY_ID || record.policy_contract_sha256 !== organizationMemberReadablePolicyContractSha256() || record.http_method !== 'POST' || record.http_path !== ORGANIZATION_API_PERMISSION_CHECKS_PATH) fail(`${label} policy or operation is unsupported`); for (const field of ['policy_contract_sha256','release_draft_sha256','approval_presentation_sha256'] as const) assertDigest(record[field],`${label} ${field}`);
}
export function validateOrganizationMemberReadablePermissionCheckRequest(value: unknown): OrganizationMemberReadablePermissionCheckRequestV3 { const label='organization-member permission check request'; assertOnlyEnumerableDataProperties(value,label); let bytes:Uint8Array; try { bytes=canonicalJsonBytes(value); } catch (error) { fail(`${label} is not canonicalizable`,error); } if (bytes.byteLength > MAX_ORGANIZATION_API_BODY_BYTES) fail(`${label} exceeds its canonical byte bound`); const record=asRecord(value,label); assertExactKeys(record,requestKeys,label); if (record.schema_version !== 3 || record.kind !== 'echo-organization-permission-check-request') fail(`${label} version or kind is unsupported`); assertRequestFields(record,label); assertDigest(record.provider_event_sha256,`${label} provider_event_sha256`); if (record.provider_event_sha256 !== organizationMemberReadablePermissionProviderEventSha256(record as unknown as OrganizationMemberReadablePermissionCheckRequestV3)) fail(`${label} provider_event_sha256 does not match its event`); assertTimestamp(record.requested_at,`${label} requested_at`); const integrity=validateIntegrity(record.integrity,label); if (integrity.key_id !== record.installation_key_id) fail(`${label} signature key does not match installation key`); return {...record,integrity} as unknown as OrganizationMemberReadablePermissionCheckRequestV3; }
export function verifyOrganizationMemberReadablePermissionCheckRequest(value: unknown,key:P256SigningKeyDescriptor): OrganizationMemberReadablePermissionCheckRequestV3 { const request=validateOrganizationMemberReadablePermissionCheckRequest(value); const publicKey=verifyP256SigningKeyDescriptor(key); if (request.installation_key_id !== key.key_id || request.integrity.key_id !== key.key_id) throw new Error('organization API: organization-member permission request does not match installation key'); verifySignedDocument(request,publicKey,key.key_id); return request; }
export function organizationMemberReadablePermissionCheckRequestSha256(value: unknown,key:P256SigningKeyDescriptor): Sha256Digest { return canonicalSha256(verifyOrganizationMemberReadablePermissionCheckRequest(value,key)); }
export interface CreateOrganizationMemberReadablePermissionCheckRequestInput extends Omit<OrganizationMemberReadablePermissionProviderEventInput,'installation_key_id'|'http_method'|'http_path'|'action'|'policy_id'|'policy_contract_sha256'> { request_id:string; installation_signing_key:P256SigningKeyDescriptor; requested_at:string }
export async function createOrganizationMemberReadablePermissionCheckRequest(input:CreateOrganizationMemberReadablePermissionCheckRequestInput,sign:CanonicalPayloadSigner): Promise<OrganizationMemberReadablePermissionCheckRequestV3> { verifyP256SigningKeyDescriptor(input.installation_signing_key); const event=organizationMemberReadablePermissionProviderEvent({...input,installation_key_id:input.installation_signing_key.key_id,action:'approve',policy_id:ORGANIZATION_MEMBER_READABLE_POLICY_ID,policy_contract_sha256:organizationMemberReadablePolicyContractSha256(),http_method:'POST',http_path:ORGANIZATION_API_PERMISSION_CHECKS_PATH}); const payload:OrganizationMemberReadablePermissionCheckRequestPayloadV3={schema_version:3,kind:'echo-organization-permission-check-request',request_id:input.request_id,...event,provider_event_sha256:organizationMemberReadablePermissionProviderEventSha256(event),requested_at:input.requested_at}; return validateOrganizationMemberReadablePermissionCheckRequest(await createSignedDocumentWithKey(payload,input.installation_signing_key.key_id,sign)); }
const decisionKeys=['schema_version','kind','request_sha256','provider_event_sha256','allowed','reason_code','policy_id','policy_contract_sha256','principal_id','membership_id','adapter_binding_id','permission_grant_id','evaluated_at','authorization_audit_event_id','authorization_audit_entry_sha256','release_draft_sha256','approval_presentation_sha256','semantic_intent_sha256','message_presentation_sha256'] as const;
export function validateOrganizationMemberReadablePermissionCheckDecision(value:unknown): OrganizationMemberReadablePermissionCheckDecisionV3 { const label='organization-member permission check decision'; assertOnlyEnumerableDataProperties(value,label); const record=asRecord(value,label); assertExactKeys(record,decisionKeys,label); if (record.schema_version !== 3 || record.kind !== 'echo-organization-permission-check-decision' || record.policy_id !== ORGANIZATION_MEMBER_READABLE_POLICY_ID || record.policy_contract_sha256 !== organizationMemberReadablePolicyContractSha256() || typeof record.allowed !== 'boolean') fail(`${label} literals are unsupported`); assertDigest(record.request_sha256,`${label} request_sha256`); assertDigest(record.provider_event_sha256,`${label} provider_event_sha256`); assertTimestamp(record.evaluated_at,`${label} evaluated_at`); if (record.allowed) { if (record.reason_code !== ORGANIZATION_MEMBER_READABLE_ALLOW_REASON_CODE) fail(`${label} allow reason is unsupported`); for (const [field,prefix] of [["principal_id","prn"],["membership_id","mem"],["adapter_binding_id","bnd"],["authorization_audit_event_id","aud"]] as const) assertId(record[field],prefix,`${label} ${field}`); assertId(record.permission_grant_id,'pgr',`${label} permission_grant_id`); for (const field of ['authorization_audit_entry_sha256','release_draft_sha256','approval_presentation_sha256','semantic_intent_sha256','message_presentation_sha256'] as const) assertDigest(record[field],`${label} ${field}`); } else { for (const field of ['principal_id','membership_id','adapter_binding_id','permission_grant_id','authorization_audit_event_id','authorization_audit_entry_sha256','release_draft_sha256','approval_presentation_sha256','semantic_intent_sha256','message_presentation_sha256'] as const) if (record[field] !== null) fail(`${label} denial ${field} must be null`); if (typeof record.reason_code !== 'string' || !ORGANIZATION_MEMBER_READABLE_PERMISSION_DENIAL_REASON_CODES.includes(record.reason_code as OrganizationMemberReadablePermissionDenialReasonCodeV3)) fail(`${label} denial reason is invalid`); } return record as unknown as OrganizationMemberReadablePermissionCheckDecisionV3; }
