import { createSignedDocumentWithKey, verifyP256SigningKeyDescriptor, verifySignedDocument } from "@echo-brain/federation-protocol";
import type { P256SigningKeyDescriptor } from "@echo-brain/federation-protocol";
import type { CanonicalPayloadSigner, OrganizationRecordApprovalPayloadV1, OrganizationRecordOrganizationMemberApprovalEnvelopePayloadV3, OrganizationRecordOrganizationMemberApprovalEnvelopeV3, OrganizationRecordOrganizationMemberAuthorizationV3, OrganizationRecordOrganizationMemberIntentV3, OrganizationRecordOrganizationMemberV3, OrganizationRecordSubmitterV1 } from "./contracts.js";
import type { PinnedOrganizationAuthority } from "./authority-descriptor.js";
import { resolvePinnedOrganizationAuthority } from "./authority-descriptor.js";
import { assertOrganizationRecordApprovalPayload, MAX_ORGANIZATION_RECORD_DOCUMENT_BYTES } from "./record-payload.js";
import { projectOrganizationMemberReadableReleaseDraft, organizationMemberReadableReleaseDraftSha256 } from "./organization-member-release-draft.js";
import { ORGANIZATION_MEMBER_READABLE_ALLOW_REASON_CODE, ORGANIZATION_MEMBER_READABLE_POLICY_ID, ORGANIZATION_MEMBER_READABLE_RECORD_SURFACE, assertOrganizationMemberReadableApprovalId, assertOrganizationMemberReadablePresentableText, organizationMemberReadablePolicyContractSha256 } from "./organization-member-readable-policy.js";
import { asRecord, assertDigest, assertExactKeys, assertId, assertLiteral, assertOnlyEnumerableDataProperties, assertPrefixedUuidId, assertTimestamp, canonicalSnapshot, timestampMillis, validateSignedIntegrity } from "./validation-support.js";
import { organizationProtocolValidationFailure } from "./validation-error.js";

export const ORGANIZATION_MEMBER_READABLE_RECORD_ENVELOPE_SCHEMA_VERSION = 3;
const label = "organization record organization-member envelope";
function submitter(value: unknown): OrganizationRecordSubmitterV1 { const row = asRecord(value, `${label} submitter`); assertExactKeys(row, ["installation_id", "submitted_at"], `${label} submitter`); assertId(row.installation_id, "ins", `${label} submitter installation_id`); assertTimestamp(row.submitted_at, `${label} submitter submitted_at`); return row as unknown as OrganizationRecordSubmitterV1; }
function authorization(value: unknown): OrganizationRecordOrganizationMemberAuthorizationV3 {
  const row = asRecord(value, `${label} authorization`); assertExactKeys(row, ["schema_version","kind","policy_id","policy_contract_sha256","authority_id","organization_id","enrollment_id","installation_id","request_id","approval_id","action","request_sha256","provider_event_sha256","allowed","reason_code","principal_id","membership_id","adapter_binding_id","permission_grant_id","evaluated_at","authorization_audit_event_id","authorization_audit_entry_sha256","release_draft_sha256","approval_presentation_sha256","semantic_intent_sha256","message_presentation_sha256"], `${label} authorization`);
  assertLiteral(row.schema_version, 3, `${label} authorization schema_version`); assertLiteral(row.kind, "echo-organization-authorization-evidence", `${label} authorization kind`); assertLiteral(row.policy_id, ORGANIZATION_MEMBER_READABLE_POLICY_ID, `${label} authorization policy_id`); assertDigest(row.policy_contract_sha256, `${label} authorization policy_contract_sha256`); if (row.policy_contract_sha256 !== organizationMemberReadablePolicyContractSha256()) organizationProtocolValidationFailure(`${label} authorization policy contract is unsupported`);
  for (const [field,prefix] of [["authority_id","oau"],["organization_id","org"],["enrollment_id","enr"],["installation_id","ins"],["principal_id","prn"],["membership_id","mem"],["adapter_binding_id","bnd"]] as const) assertId(row[field], prefix, `${label} authorization ${field}`);
  assertPrefixedUuidId(row.request_id, "pcr", `${label} authorization request_id`); assertOrganizationMemberReadableApprovalId(row.approval_id, `${label} authorization approval_id`); assertLiteral(row.action, "approve", `${label} authorization action`); if (row.allowed !== true) organizationProtocolValidationFailure(`${label} authorization must be an allow decision`); assertLiteral(row.reason_code, ORGANIZATION_MEMBER_READABLE_ALLOW_REASON_CODE, `${label} authorization reason_code`); assertPrefixedUuidId(row.permission_grant_id, "pgr", `${label} authorization permission_grant_id`); assertTimestamp(row.evaluated_at, `${label} authorization evaluated_at`); assertPrefixedUuidId(row.authorization_audit_event_id, "aud", `${label} authorization authorization_audit_event_id`); for (const field of ["request_sha256","provider_event_sha256","authorization_audit_entry_sha256","release_draft_sha256","approval_presentation_sha256","semantic_intent_sha256","message_presentation_sha256"] as const) assertDigest(row[field], `${label} authorization ${field}`);
  return row as unknown as OrganizationRecordOrganizationMemberAuthorizationV3;
}
function reviewer(value: unknown, approvalId: string, installationId: string): OrganizationRecordOrganizationMemberV3 { const row = asRecord(value, `${label} reviewer`); assertExactKeys(row, ["principal_id","membership_id","reviewed_by","authorization"], `${label} reviewer`); assertId(row.principal_id,"prn",`${label} reviewer principal_id`); assertId(row.membership_id,"mem",`${label} reviewer membership_id`); assertOrganizationMemberReadablePresentableText(row.reviewed_by, `${label} reviewer reviewed_by`, 256); const proof=authorization(row.authorization); if (proof.approval_id !== approvalId || proof.installation_id !== installationId || proof.principal_id !== row.principal_id || proof.membership_id !== row.membership_id) organizationProtocolValidationFailure(`${label} authorization does not bind this exact submission`); return row as unknown as OrganizationRecordOrganizationMemberV3; }
export function assertOrganizationMemberReadableApprovalEnvelopeSnapshot(record: Record<string, unknown>, ignored = label): void {
  assertExactKeys(record,["schema_version","kind","event_type","envelope_id","idempotency_key","payload","reviewer","intent","submitter","integrity"],ignored); assertLiteral(record.schema_version,3,`${ignored} schema_version`); assertLiteral(record.kind,"echo-organization-record-envelope",`${ignored} kind`); assertLiteral(record.event_type,"approval",`${ignored} event_type`); assertId(record.envelope_id,"rec",`${ignored} envelope_id`); assertOrganizationMemberReadableApprovalId(record.idempotency_key,`${ignored} idempotency_key`); const sent=submitter(record.submitter); const actor=reviewer(record.reviewer,record.idempotency_key as string,sent.installation_id); const intent=asRecord(record.intent,`${ignored} intent`); assertExactKeys(intent,["schema_version","visibility","policy_id","policy_contract_sha256","provenance"],`${ignored} intent`); assertLiteral(intent.schema_version,1,`${ignored} intent schema_version`); assertLiteral(intent.visibility,"organization-member-readable",`${ignored} intent visibility`); assertLiteral(intent.policy_id,ORGANIZATION_MEMBER_READABLE_POLICY_ID,`${ignored} intent policy_id`); assertLiteral(intent.policy_contract_sha256,actor.authorization.policy_contract_sha256,`${ignored} intent policy_contract_sha256`); const provenance=asRecord(intent.provenance,`${ignored} intent provenance`); assertExactKeys(provenance,["kind","semantic_intent_sha256"],`${ignored} intent provenance`); assertLiteral(provenance.kind,"approval-surface-confirmation-v1",`${ignored} intent provenance kind`); assertLiteral(provenance.semantic_intent_sha256,actor.authorization.semantic_intent_sha256,`${ignored} intent provenance semantic_intent_sha256`); validateSignedIntegrity(record.integrity,`${ignored} integrity`);
  assertOrganizationRecordApprovalPayload(record.payload,`${ignored} payload`); const payload=record.payload as OrganizationRecordApprovalPayloadV1; assertLiteral(payload.surface,ORGANIZATION_MEMBER_READABLE_RECORD_SURFACE,`${ignored} payload surface`); if (organizationMemberReadableReleaseDraftSha256(projectOrganizationMemberReadableReleaseDraft({approval_id:record.idempotency_key as string,brief:payload.brief})) !== actor.authorization.release_draft_sha256) organizationProtocolValidationFailure(`${ignored} payload does not reproduce the approved release draft`); if (payload.reviewed_at !== actor.authorization.evaluated_at || timestampMillis(sent.submitted_at,`${ignored} submitted_at`) < timestampMillis(payload.reviewed_at,`${ignored} reviewed_at`)) organizationProtocolValidationFailure(`${ignored} approval time binding is invalid`);
}
export function validateOrganizationRecordOrganizationMemberApprovalEnvelope(value: unknown): OrganizationRecordOrganizationMemberApprovalEnvelopeV3 { assertOnlyEnumerableDataProperties(value,label); const record=asRecord(canonicalSnapshot(value,label,MAX_ORGANIZATION_RECORD_DOCUMENT_BYTES),label); assertOrganizationMemberReadableApprovalEnvelopeSnapshot(record); return record as unknown as OrganizationRecordOrganizationMemberApprovalEnvelopeV3; }
export function verifyOrganizationRecordOrganizationMemberApprovalEnvelope(value: unknown, pinned: PinnedOrganizationAuthority, key: P256SigningKeyDescriptor): OrganizationRecordOrganizationMemberApprovalEnvelopeV3 { const envelope=validateOrganizationRecordOrganizationMemberApprovalEnvelope(value); const authority=resolvePinnedOrganizationAuthority(pinned); if (envelope.reviewer.authorization.authority_id !== authority.authority_id || envelope.reviewer.authorization.organization_id !== authority.organization_id) throw new Error("organization record envelope does not match the pinned authority"); const verified=verifyP256SigningKeyDescriptor(key); if (envelope.integrity.key_id !== key.key_id) throw new Error("organization record envelope does not match the installation key"); verifySignedDocument(envelope,verified,key.key_id); return envelope; }
export interface CreateOrganizationRecordOrganizationMemberApprovalEnvelopeInput { envelope_id:string; idempotency_key:string; payload:OrganizationRecordApprovalPayloadV1; reviewer:OrganizationRecordOrganizationMemberV3; intent:OrganizationRecordOrganizationMemberIntentV3; submitter:OrganizationRecordSubmitterV1; installation_signing_key:P256SigningKeyDescriptor }
export async function createOrganizationRecordOrganizationMemberApprovalEnvelope(input: CreateOrganizationRecordOrganizationMemberApprovalEnvelopeInput, pinned: PinnedOrganizationAuthority, sign: CanonicalPayloadSigner): Promise<OrganizationRecordOrganizationMemberApprovalEnvelopeV3> { const payload: OrganizationRecordOrganizationMemberApprovalEnvelopePayloadV3={schema_version:3,kind:"echo-organization-record-envelope",event_type:"approval",envelope_id:input.envelope_id,idempotency_key:input.idempotency_key,payload:input.payload,reviewer:input.reviewer,intent:input.intent,submitter:input.submitter}; return verifyOrganizationRecordOrganizationMemberApprovalEnvelope(await createSignedDocumentWithKey(payload,input.installation_signing_key.key_id,sign),pinned,input.installation_signing_key); }
export function organizationRecordOrganizationMemberIntent(semantic: string): OrganizationRecordOrganizationMemberIntentV3 { assertDigest(semantic,"organization-member intent semantic_intent_sha256"); return {schema_version:1,visibility:"organization-member-readable",policy_id:ORGANIZATION_MEMBER_READABLE_POLICY_ID,policy_contract_sha256:organizationMemberReadablePolicyContractSha256(),provenance:{kind:"approval-surface-confirmation-v1",semantic_intent_sha256:semantic as `sha256:${string}`}}; }
