/** Slack-owned V2 approval resolution. V1 remains decoded only by its V1 module. */
import { canonicalSha256 } from "@echo-brain/organization-control-plane/canonical/canonical-json";
import {
  PRIVATE_APPROVAL_AUTHORIZATION_ALLOW_V2_KIND,
  PRIVATE_APPROVAL_PENDING_V2_KIND,
  PRIVATE_APPROVAL_RESOLUTION_V2_KIND,
  privateApprovalPolicyBindingV2,
  privateApprovalTranscriptSourceV1,
  validatePrivateApprovalResolutionCommandV2,
  type PrivateApprovalPolicyBindingV2,
  type PrivateApprovalResolutionCommandV2,
  type PrivateApprovalTranscriptSourceV1,
} from "@echo-brain/organization-control-plane/application/private-approval-policy-resolution-core-v2";
import {
  privateApprovalAssignee, privateApprovalCommitment, privateApprovalDigest,
  privateApprovalExactRecord, privateApprovalIdentifier,
  samePrivateApprovalAssignee, samePrivateApprovalCommitment,
  type PrivateApprovalAssigneeV1, type PrivateApprovalCommitmentV1,
} from "@echo-brain/organization-control-plane/application/private-approval-policy-resolution-core-v1";
import type { ApprovalContractSha256 } from "@echo-brain/organization-control-plane/application/record-visibility-policy-contracts-v1";
import type { PrivateApprovalSlackIdentityLinkV1 } from "./private-approval-policy-resolution-v1.js";

export interface PrivateApprovalEligibleProjectV2 { readonly project_id:string; readonly project_membership_id:string; readonly name:string }
export interface PendingPrivateApprovalV2 extends PrivateApprovalCommitmentV1 {
  readonly schema_version:2; readonly kind:typeof PRIVATE_APPROVAL_PENDING_V2_KIND;
  readonly assigned_owner:PrivateApprovalAssigneeV1; readonly assigned_owner_slack_identity_link:PrivateApprovalSlackIdentityLinkV1;
  readonly eligible_projects:readonly PrivateApprovalEligibleProjectV2[]; readonly transcript_source:PrivateApprovalTranscriptSourceV1;
}
export interface PrivateApprovalAuthorizationAllowV2 extends PrivateApprovalCommitmentV1 {
  readonly schema_version:2; readonly kind:typeof PRIVATE_APPROVAL_AUTHORIZATION_ALLOW_V2_KIND;
  readonly authorized_assignee:PrivateApprovalAssigneeV1; readonly current_slack_identity_link:PrivateApprovalSlackIdentityLinkV1; readonly authorization_proof_sha256:ApprovalContractSha256;
}
export interface PrivateApprovalResolutionV2 extends PrivateApprovalCommitmentV1 {
  readonly schema_version:2; readonly kind:typeof PRIVATE_APPROVAL_RESOLUTION_V2_KIND; readonly command_id:string;
  readonly final_approver:PrivateApprovalAssigneeV1; readonly current_slack_identity_link:PrivateApprovalSlackIdentityLinkV1; readonly authorization_proof_sha256:ApprovalContractSha256;
  readonly action:"approve"|"reject"; readonly comment:string|null; readonly selected_project_ids:readonly string[]; readonly share_transcript:boolean; readonly canonical_record_policy:PrivateApprovalPolicyBindingV2|null;
}
const PROJECT=/^prj_[0-9a-f-]{36}$/; const MEMBERSHIP=/^pgm_[0-9a-f-]{36}$/;
function bad(message:string):never { throw new Error(`private approval V2 ${message}`); }
function link(value:unknown,label:string):PrivateApprovalSlackIdentityLinkV1 { const r=privateApprovalExactRecord(value,["provider","external_identity_link_id","external_identity_link_contract_sha256","provider_subject_id"],label); if(r.provider!=="slack"||typeof r.external_identity_link_id!=="string"||!/^clm_[A-Za-z0-9][A-Za-z0-9._:-]{0,251}$/.test(r.external_identity_link_id)||typeof r.provider_subject_id!=="string"||!/^[UW][A-Z0-9]{2,255}$/.test(r.provider_subject_id)) bad(`${label} link invalid`); privateApprovalDigest(r.external_identity_link_contract_sha256,`${label} link digest`); return Object.freeze({provider:"slack",external_identity_link_id:r.external_identity_link_id,external_identity_link_contract_sha256:r.external_identity_link_contract_sha256,provider_subject_id:r.provider_subject_id}); }
function sameLink(left:PrivateApprovalSlackIdentityLinkV1,right:PrivateApprovalSlackIdentityLinkV1):boolean { return left.provider===right.provider&&left.external_identity_link_id===right.external_identity_link_id&&left.external_identity_link_contract_sha256===right.external_identity_link_contract_sha256&&left.provider_subject_id===right.provider_subject_id; }
function projects(value:unknown):readonly PrivateApprovalEligibleProjectV2[] { if(!Array.isArray(value)||value.length>100)bad("eligible projects invalid"); let prior=""; return Object.freeze(value.map((item,index)=>{const r=privateApprovalExactRecord(item,["project_id","project_membership_id","name"],`eligible project ${index}`); if(typeof r.project_id!=="string"||!PROJECT.test(r.project_id)||typeof r.project_membership_id!=="string"||!MEMBERSHIP.test(r.project_membership_id)||typeof r.name!=="string"||r.name.trim()!==r.name||r.name.length===0||r.name.length>200||r.project_id<=prior)bad("eligible projects invalid"); prior=r.project_id; return Object.freeze({project_id:r.project_id,project_membership_id:r.project_membership_id,name:r.name});})); }
export function validatePendingPrivateApprovalV2(value:unknown):PendingPrivateApprovalV2 { const r=privateApprovalExactRecord(value,["schema_version","kind","approval_id","organization_id","candidate_sha256","frozen_card_sha256","approved_snapshot_sha256","assigned_owner","assigned_owner_slack_identity_link","eligible_projects","transcript_source"],"pending V2"); if(r.schema_version!==2||r.kind!==PRIVATE_APPROVAL_PENDING_V2_KIND)bad("pending schema"); return Object.freeze({schema_version:2,kind:PRIVATE_APPROVAL_PENDING_V2_KIND,...privateApprovalCommitment(r,"pending V2"),assigned_owner:privateApprovalAssignee(r.assigned_owner,"pending owner"),assigned_owner_slack_identity_link:link(r.assigned_owner_slack_identity_link,"pending owner"),eligible_projects:projects(r.eligible_projects),transcript_source:privateApprovalTranscriptSourceV1(r.transcript_source,"pending transcript")}); }
export function validatePrivateApprovalAuthorizationAllowV2(value:unknown):PrivateApprovalAuthorizationAllowV2 { const r=privateApprovalExactRecord(value,["schema_version","kind","approval_id","organization_id","candidate_sha256","frozen_card_sha256","approved_snapshot_sha256","authorized_assignee","current_slack_identity_link","authorization_proof_sha256"],"allow V2"); if(r.schema_version!==2||r.kind!==PRIVATE_APPROVAL_AUTHORIZATION_ALLOW_V2_KIND)bad("allow schema"); privateApprovalDigest(r.authorization_proof_sha256,"allow proof"); return Object.freeze({schema_version:2,kind:PRIVATE_APPROVAL_AUTHORIZATION_ALLOW_V2_KIND,...privateApprovalCommitment(r,"allow V2"),authorized_assignee:privateApprovalAssignee(r.authorized_assignee,"allow actor"),current_slack_identity_link:link(r.current_slack_identity_link,"allow actor"),authorization_proof_sha256:r.authorization_proof_sha256}); }
export function resolvePrivateApprovalPolicyV2(input:{readonly pending:PendingPrivateApprovalV2;readonly command:PrivateApprovalResolutionCommandV2;readonly authorization_allow:PrivateApprovalAuthorizationAllowV2;readonly selected_projects_current:readonly {readonly project_id:string;readonly project_membership_id:string}[]}):PrivateApprovalResolutionV2 { const p=validatePendingPrivateApprovalV2(input.pending), c=validatePrivateApprovalResolutionCommandV2(input.command), a=validatePrivateApprovalAuthorizationAllowV2(input.authorization_allow); if(c.approval_id!==p.approval_id||!samePrivateApprovalCommitment(a,p)||!samePrivateApprovalAssignee(a.authorized_assignee,p.assigned_owner)||!sameLink(a.current_slack_identity_link,p.assigned_owner_slack_identity_link))bad("authorization mismatch"); const selected=p.eligible_projects.filter(x=>c.selected_project_ids.includes(x.project_id)); if(selected.length!==c.selected_project_ids.length||input.selected_projects_current.length!==selected.length||selected.some((x,i)=>x.project_id!==input.selected_projects_current[i]?.project_id||x.project_membership_id!==input.selected_projects_current[i]?.project_membership_id))bad("selected project grant changed"); const policy=c.action==="approve"?privateApprovalPolicyBindingV2({policy_id:c.selected_policy_id!,approver:a.authorized_assignee,audience_project_ids:c.selected_project_ids,association_project_ids:c.selected_project_ids,share_transcript:c.share_transcript,transcript_source:p.transcript_source,policy_consequence_sha256:canonicalSha256({schema_version:2,kind:"echo-private-slack-block-approval-consequence-v2",policy_id:c.selected_policy_id!,audience_project_ids:c.selected_project_ids,association_project_ids:c.selected_project_ids,share_transcript:c.share_transcript,transcript_source:p.transcript_source})}):null; return Object.freeze({schema_version:2,kind:PRIVATE_APPROVAL_RESOLUTION_V2_KIND,command_id:c.command_id,approval_id:p.approval_id,organization_id:p.organization_id,candidate_sha256:p.candidate_sha256,frozen_card_sha256:p.frozen_card_sha256,approved_snapshot_sha256:p.approved_snapshot_sha256,final_approver:a.authorized_assignee,current_slack_identity_link:a.current_slack_identity_link,authorization_proof_sha256:a.authorization_proof_sha256,action:c.action,comment:c.comment,selected_project_ids:c.selected_project_ids,share_transcript:c.share_transcript,canonical_record_policy:policy}); }
export function validatePrivateApprovalResolutionV2(value: unknown): PrivateApprovalResolutionV2 {
  const r = privateApprovalExactRecord(value,["schema_version","kind","command_id","approval_id","organization_id","candidate_sha256","frozen_card_sha256","approved_snapshot_sha256","final_approver","current_slack_identity_link","authorization_proof_sha256","action","comment","selected_project_ids","share_transcript","canonical_record_policy"],"resolution V2");
  if(r.schema_version!==2||r.kind!==PRIVATE_APPROVAL_RESOLUTION_V2_KIND||r.action!=="approve"&&r.action!=="reject"||typeof r.share_transcript!=="boolean") bad("resolution schema");
  privateApprovalIdentifier(r.command_id,"resolution command");
  const commitment=privateApprovalCommitment(r,"resolution V2"), approver=privateApprovalAssignee(r.final_approver,"resolution actor");
  privateApprovalDigest(r.authorization_proof_sha256,"resolution proof");
  const command=validatePrivateApprovalResolutionCommandV2({schema_version:2,command_id:r.command_id,approval_id:r.approval_id,action:r.action,selected_policy_id:r.canonical_record_policy===null?null:(r.canonical_record_policy as {policy_id:unknown}).policy_id,selected_project_ids:r.selected_project_ids,share_transcript:r.share_transcript,comment:r.comment});
  if(command.action==="approve"&&r.canonical_record_policy===null||command.action==="reject"&&r.canonical_record_policy!==null) bad("resolution policy");
  let policy: PrivateApprovalPolicyBindingV2|null=null;
  if(r.canonical_record_policy!==null){ const x=privateApprovalExactRecord(r.canonical_record_policy,["policy_id","policy_contract_sha256","policy_consequence_sha256","restricted_reader","audience_project_ids","association_project_ids","share_transcript","transcript_source"],"resolution policy"); const reader=x.restricted_reader===null?null:privateApprovalAssignee(x.restricted_reader,"resolution reader"); const source=privateApprovalTranscriptSourceV1(x.transcript_source,"resolution source"); const rebuilt=privateApprovalPolicyBindingV2({policy_id:x.policy_id as never,approver:approver,audience_project_ids:x.audience_project_ids as readonly string[],association_project_ids:x.association_project_ids as readonly string[],share_transcript:x.share_transcript as boolean,transcript_source:source,policy_consequence_sha256:x.policy_consequence_sha256 as ApprovalContractSha256}); const expectedConsequence=canonicalSha256({schema_version:2,kind:"echo-private-slack-block-approval-consequence-v2",policy_id:rebuilt.policy_id,audience_project_ids:rebuilt.audience_project_ids,association_project_ids:rebuilt.association_project_ids,share_transcript:rebuilt.share_transcript,transcript_source:rebuilt.transcript_source}); if(rebuilt.policy_contract_sha256!==x.policy_contract_sha256||rebuilt.policy_consequence_sha256!==x.policy_consequence_sha256||rebuilt.policy_consequence_sha256!==expectedConsequence||((reader===null)!==(rebuilt.restricted_reader===null))||(reader!==null&&!samePrivateApprovalAssignee(reader,rebuilt.restricted_reader!))||rebuilt.policy_id!==command.selected_policy_id||rebuilt.audience_project_ids.length!==command.selected_project_ids.length||rebuilt.audience_project_ids.some((id,index)=>id!==command.selected_project_ids[index])||rebuilt.association_project_ids.length!==command.selected_project_ids.length||rebuilt.association_project_ids.some((id,index)=>id!==command.selected_project_ids[index])||rebuilt.share_transcript!==command.share_transcript)bad("resolution policy"); policy=rebuilt; }
  return Object.freeze({schema_version:2,kind:PRIVATE_APPROVAL_RESOLUTION_V2_KIND,command_id:command.command_id,...commitment,final_approver:approver,current_slack_identity_link:link(r.current_slack_identity_link,"resolution actor"),authorization_proof_sha256:r.authorization_proof_sha256,action:command.action,comment:command.comment,selected_project_ids:command.selected_project_ids,share_transcript:command.share_transcript,canonical_record_policy:policy});
}
